### ISSUE TITLE
working example

### ISSUE THREAD

**Issue by vtmocanu** [dougsong/provider-proxmoxve#6]
hey @dougsong, is this provider working?
i want to use it but don't know exactly how to set up the proxmox API URL.
this is what I have:
```
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-proxmoxve
spec:
  package: xpkg.upbound.io/zhenran/provider-proxmoxve:v0.0.1
---
apiVersion: proxmoxve.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-creds
      namespace: crossplane-system
      key: credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "username": "REDACTED",
      "password": "REDACTED"
    }
---
apiVersion: vm.proxmoxve.upbound.io/v1alpha1
kind: Qemu
metadata:
  annotations:
    meta.upbound.io/example-id: vm/v1alpha1/qemu
  labels:
    testing.upbound.io/example-name: resource-name
  name: resource-name
spec:
  forProvider:
    iso: ubuntu-20.04.1-live-server-amd64.iso
    name: cross-vm
    targetNode: prx1
```

thank you!
